version: 0.0
os: linux

files:
  - source: .
    destination: /home/ubuntu/app

hooks:
  ApplicationStop:
    - location: scripts/stop_app.sh
      timeout: 60
      runas: root

  BeforeInstall:
    - location: scripts/pull_image.sh
      timeout: 60
      runas: root

  ApplicationStart:
    - location: scripts/start_app.sh
      timeout: 60
      runas: root
