name: Deploy to AWS

on:
  push:
    branches:
      - main  # Change if using another branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t mammarraza/blog:latest .
          docker push mammarraza/blog:latest

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Notify AWS CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name blog-app \
            --deployment-group-name ammar-dg \
            --revision "{\"revisionType\": \"AppSpecContent\", \"appSpecContent\": {\"content\": \"file://appspec.yml\"}}" \
            --region us-east-1
